import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import NavigationConnected from '@/app/(shopping)/NavigationConnected'
import Providers from '@/app/(shopping)/components/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  command,
}: {
  children: ReactNode
  command: ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <NavigationConnected />

          {children}
          {command}
        </Providers>
      </body>
    </html>
  )
}
